input_features:
  -
    name: mnth
    type: numerical
  -
    name: day
    type: numerical    
  -
    name: amnt
    type: numerical   
  -
    name: acnt
    type: category   
  -
    name: desc
    type: text
    level: char
    lowercase: true
    char_sequence_length_limit: 256 
    encoder: embed
    
output_features:
  -
    name: catg
    type: category

training:
    epochs: 1000
    batch_size: 500
    early_stop: 500